spring:
  application:
    name: shop

  security:
    user:
      name: admin
      password: 1234

  datasource:
    url: jdbc:oracle:thin:@192.168.30.5:1521:XE
    username: jsl22
    password: 1234
    driver-class-name: oracle.jdbc.OracleDriver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.OracleDialect